apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: harbor-registry-snapcontent-wave5
  labels:
    migration-wave: "5"
    source-namespace: harbor-system
    target-namespace: staging-platform-harbor
spec:
  deletionPolicy: Retain
  driver: ebs.csi.aws.com
  source:
    snapshotHandle: snap-0b2eeeb4a68bf7aba
  volumeSnapshotRef:
    name: harbor-registry-snapshot-wave5
    namespace: staging-platform-harbor
