apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: harbor-registry-snapshot-wave5
  namespace: staging-platform-harbor
  labels:
    migration-wave: "5"
    source-pvc: harbor-registry
spec:
  volumeSnapshotClassName: ebs-csi-snapshot-class
  source:
    volumeSnapshotContentName: harbor-registry-snapcontent-wave5
