---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarqube-postgresql
  namespace: staging-platform-sonarqube
  labels:
    app.kubernetes.io/managed-by: terraform
    app.kubernetes.io/name: sonarqube-postgresql
spec:
  data:
  - remoteRef:
      key: secret/data/sonarqube/postgresql
      property: password
    secretKey: postgresql-password
  - remoteRef:
      key: secret/data/sonarqube/postgresql
      property: username
    secretKey: username
  - remoteRef:
      key: secret/data/sonarqube/postgresql
      property: host
    secretKey: host
  - remoteRef:
      key: secret/data/sonarqube/postgresql
      property: port
    secretKey: port
  - remoteRef:
      key: secret/data/sonarqube/postgresql
      property: database
    secretKey: database
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: sonarqube-postgresql
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarqube-sp-saml
  namespace: staging-platform-sonarqube
  annotations:
    force-sync: "1771458397"
spec:
  data:
  - remoteRef:
      key: secret/data/sonarqube/saml
      property: sp_private_key_pkcs8
    secretKey: sp_private_key_pkcs8
  - remoteRef:
      key: secret/data/sonarqube/saml
      property: sp_certificate
    secretKey: sp_certificate
  - remoteRef:
      key: secret/data/sonarqube/gitlab
      property: application_id
    secretKey: gitlab_application_id
  - remoteRef:
      key: secret/data/sonarqube/gitlab
      property: application_secret
    secretKey: gitlab_application_secret
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: sonarqube-sp-saml
    template:
      data:
        secret.properties: |
          sonar.auth.saml.sp.certificate.secured={{ .sp_certificate }}
          sonar.auth.saml.sp.privateKey.secured={{ .sp_private_key_pkcs8 }}
          sonar.auth.gitlab.applicationId={{ .gitlab_application_id }}
          sonar.auth.gitlab.secret={{ .gitlab_application_secret }}
      engineVersion: v2
      mergePolicy: Replace
