apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: prometheus-db-snapcontent-wave5
  labels:
    migration-wave: "5"
    source-namespace: monitoring
    target-namespace: staging-observability-monitoring
spec:
  deletionPolicy: Retain
  driver: ebs.csi.aws.com
  source:
    snapshotHandle: snap-0c2ac1b56c6196c8d
  volumeSnapshotRef:
    name: prometheus-db-snapshot-wave5
    namespace: staging-observability-monitoring
