apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: loki-write-1-snapcontent-wave5
  labels:
    migration-wave: "5"
    source-namespace: monitoring
    target-namespace: staging-observability-monitoring
spec:
  deletionPolicy: Retain
  driver: ebs.csi.aws.com
  source:
    snapshotHandle: snap-0bf55521b350e3b8c
  volumeSnapshotRef:
    name: loki-write-1-snapshot-wave5
    namespace: staging-observability-monitoring
