apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-loki-backend-0
  namespace: staging-observability-monitoring
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: backend
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 10Gi
  dataSource:
    name: loki-backend-0-snapshot-wave5
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
