apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-loki-write-0
  namespace: staging-observability-monitoring
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: write
    migration-note: "fresh-pvc-snapshot-failed"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 10Gi
