apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-kube-prometheus-stack-alertmanager-db-alertmanager-kube-prometheus-stack-alertmanager-0
  namespace: staging-observability-monitoring
  labels:
    app.kubernetes.io/name: alertmanager
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 2Gi
  dataSource:
    name: alertmanager-snapshot-wave5
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
