apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-oidc-credentials
  namespace: staging-observability-monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  refreshInterval: 1h
  target:
    name: grafana-oidc-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: client_id
    remoteRef:
      key: secret/data/grafana/oidc
      property: client_id
  - secretKey: client_secret
    remoteRef:
      key: secret/data/grafana/oidc
      property: client_secret
