apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki
  namespace: staging-observability-monitoring
  labels:
    app.kubernetes.io/component: logging
    app.kubernetes.io/managed-by: terraform
    app.kubernetes.io/name: loki
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::891377105802:role/LokiS3Role-k8s-platform-prod
automountServiceAccountToken: true
