apiVersion: v1
kind: ServiceAccount
metadata:
  name: tempo
  namespace: staging-observability-monitoring
  labels:
    app.kubernetes.io/component: tracing
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/managed-by: terraform
    app.kubernetes.io/name: tempo
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::891377105802:role/TempoS3Role-k8s-platform-prod
automountServiceAccountToken: true
