apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-admin-credentials
  namespace: staging-platform-keycloak
  labels:
    app.kubernetes.io/instance: k8s-platform-prod-keycloak
    app.kubernetes.io/managed-by: terraform
    app.kubernetes.io/name: keycloak
  annotations:
    description: Keycloak admin credentials synced from Vault KV v2 (V-006)
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: keycloak-admin-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      metadata:
        labels:
          app.kubernetes.io/instance: k8s-platform-prod-keycloak
          app.kubernetes.io/name: keycloak
  data:
    - secretKey: username
      remoteRef:
        key: secret/data/keycloak/admin
        property: username
    - secretKey: password
      remoteRef:
        key: secret/data/keycloak/admin
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-postgresql-credentials
  namespace: staging-platform-keycloak
  labels:
    app.kubernetes.io/instance: k8s-platform-prod-keycloak
    app.kubernetes.io/managed-by: terraform
    app.kubernetes.io/name: keycloak
  annotations:
    description: Keycloak PostgreSQL credentials synced from Vault KV v2
    force-sync: "1771503795"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: keycloak-postgresql-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      metadata:
        labels:
          app.kubernetes.io/instance: k8s-platform-prod-keycloak
          app.kubernetes.io/name: keycloak
  data:
    - secretKey: password
      remoteRef:
        key: secret/data/keycloak/postgresql
        property: password
    - secretKey: username
      remoteRef:
        key: secret/data/keycloak/postgresql
        property: username
    - secretKey: host
      remoteRef:
        key: secret/data/keycloak/postgresql
        property: host
    - secretKey: port
      remoteRef:
        key: secret/data/keycloak/postgresql
        property: port
    - secretKey: database
      remoteRef:
        key: secret/data/keycloak/postgresql
        property: database
