apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: gitlab-gitaly-snapshot-20260225-102034
  namespace: gitlab-staging
spec:
  volumeSnapshotClassName: ebs-csi-snapshot-class
  source:
    persistentVolumeClaimName: repo-data-gitlab-gitaly-0
