---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-gitaly-pv-restored
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: snap-0410be8148ec15725
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repo-data-gitlab-gitaly-0
  namespace: staging-platform-gitlab
  labels:
    app: gitaly
    domain: platform
    owner: platform-team
    environment: staging
    app.kubernetes.io/name: gitaly
    app.kubernetes.io/part-of: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 50Gi
  volumeName: gitlab-gitaly-pv-restored
