apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-oidc-credentials
  namespace: staging-platform-argocd
  labels:
    app.kubernetes.io/instance: k8s-platform-prod-argocd
    app.kubernetes.io/managed-by: terraform
    app.kubernetes.io/name: argocd
  annotations:
    description: ArgoCD OIDC client secret synced from Vault KV v2 (V-002)
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: argocd-oidc-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      metadata:
        labels:
          app.kubernetes.io/instance: k8s-platform-prod-argocd
          app.kubernetes.io/name: argocd
  data:
    - secretKey: client-secret
      remoteRef:
        key: secret/data/argocd/oidc
        property: client_secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-postgresql-credentials
  namespace: staging-platform-argocd
  labels:
    app.kubernetes.io/instance: k8s-platform-prod-argocd
    app.kubernetes.io/managed-by: terraform
    app.kubernetes.io/name: argocd
  annotations:
    description: ArgoCD PostgreSQL credentials synced from Vault KV v2 (V-002)
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: argocd-postgresql-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      metadata:
        labels:
          app.kubernetes.io/instance: k8s-platform-prod-argocd
          app.kubernetes.io/name: argocd
  data:
    - secretKey: password
      remoteRef:
        key: secret/data/argocd/postgresql
        property: password
    - secretKey: username
      remoteRef:
        key: secret/data/argocd/postgresql
        property: username
    - secretKey: host
      remoteRef:
        key: secret/data/argocd/postgresql
        property: host
    - secretKey: port
      remoteRef:
        key: secret/data/argocd/postgresql
        property: port
    - secretKey: database
      remoteRef:
        key: secret/data/argocd/postgresql
        property: database
