#!/bin/bash
# ApplicationSets Validation Script
# Execute este script após renovar AWS SSO credentials

set -euo pipefail

echo "========================================="
echo "ApplicationSets Validation Script"
echo "Date: $(date)"
echo "========================================="
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Step 1: Check kubectl access
echo -e "${YELLOW}[1/7] Checking kubectl access...${NC}"
if kubectl cluster-info &>/dev/null; then
    echo -e "${GREEN}✓ Kubectl access OK${NC}"
else
    echo -e "${RED}✗ Kubectl access FAILED - run: aws sso login --profile k8s-platform-staging${NC}"
    exit 1
fi
echo ""

# Step 2: Check ArgoCD namespace
echo -e "${YELLOW}[2/7] Checking ArgoCD namespace...${NC}"
if kubectl get namespace argocd &>/dev/null; then
    echo -e "${GREEN}✓ ArgoCD namespace exists${NC}"
else
    echo -e "${RED}✗ ArgoCD namespace not found${NC}"
    exit 1
fi
echo ""

# Step 3: Apply ApplicationSets
echo -e "${YELLOW}[3/7] Applying ApplicationSets...${NC}"
APPSET_DIR="$(dirname "$0")"
if kubectl apply -f "$APPSET_DIR/platform-services-multi-env.yaml" \
              -f "$APPSET_DIR/data-services-catalog.yaml" \
              -f "$APPSET_DIR/monitoring-multi-cluster.yaml"; then
    echo -e "${GREEN}✓ ApplicationSets applied${NC}"
else
    echo -e "${RED}✗ Failed to apply ApplicationSets${NC}"
    exit 1
fi
echo ""

# Wait for ApplicationSets to process
echo -e "${YELLOW}Waiting 10s for ApplicationSets to generate Applications...${NC}"
sleep 10
echo ""

# Step 4: List ApplicationSets
echo -e "${YELLOW}[4/7] Listing ApplicationSets...${NC}"
kubectl get applicationsets -n argocd
echo ""

# Step 5: List Applications generated
echo -e "${YELLOW}[5/7] Listing Applications (generated by ApplicationSets)...${NC}"
echo "Expected Applications from Git Generator:"
echo "  - observability-staging"
echo "  - observability-production"
echo "  - data-services-staging"
echo "  - data-services-production"
echo ""
echo "Expected Applications from List Generator:"
echo "  - postgresql-connection"
echo "  - redis-cluster"
echo "  - rabbitmq-cluster"
echo ""
echo "Actual Applications:"
kubectl get applications -n argocd -l managed-by=applicationset
echo ""

# Step 6: Check Application status
echo -e "${YELLOW}[6/7] Checking Application sync status...${NC}"
kubectl get applications -n argocd -l managed-by=applicationset -o wide
echo ""

# Step 7: Verify namespaces created
echo -e "${YELLOW}[7/7] Verifying auto-created namespaces...${NC}"
echo "Expected namespaces:"
echo "  - observability-staging"
echo "  - observability-production"
echo "  - data-services-staging"
echo "  - data-services-production"
echo ""
echo "Actual namespaces:"
kubectl get namespaces | grep -E '(observability|data-services)-(staging|production)' || echo "No auto-created namespaces found yet"
echo ""

# Summary
echo "========================================="
echo -e "${GREEN}Validation Complete!${NC}"
echo "========================================="
echo ""
echo "Next steps:"
echo "  1. Check ArgoCD UI: https://argocd.platform.internal"
echo "  2. Navigate to Settings → ApplicationSets"
echo "  3. Verify Applications are syncing"
echo "  4. Check logs if any Application is OutOfSync:"
echo "     kubectl logs -n argocd -l app.kubernetes.io/name=argocd-applicationset-controller"
echo ""
echo "Troubleshooting:"
echo "  - If Applications not generated: check generator paths match Git structure"
echo "  - If Applications OutOfSync: check AppProject destinations allow namespaces"
echo "  - If namespaces not created: check syncPolicy.syncOptions includes CreateNamespace=true"
echo ""
