apiVersion: v1
items:
- apiVersion: external-secrets.io/v1beta1
  kind: ExternalSecret
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"external-secrets.io/v1beta1","kind":"ExternalSecret","metadata":{"annotations":{},"creationTimestamp":"2026-02-19T13:04:23Z","generation":1,"name":"gitlab-ci-credentials","namespace":"gitlab-staging","resourceVersion":"11371701","uid":"ea558819-b98d-4e18-9f91-481abe8d9acd"},"spec":{"data":[{"remoteRef":{"conversionStrategy":"Default","decodingStrategy":"None","key":"secret/data/gitlab/ci-variables","metadataPolicy":"None","property":"harbor_registry_url"},"secretKey":"HARBOR_REGISTRY"},{"remoteRef":{"conversionStrategy":"Default","decodingStrategy":"None","key":"secret/data/gitlab/ci-variables","metadataPolicy":"None","property":"harbor_robot_user"},"secretKey":"HARBOR_USER"},{"remoteRef":{"conversionStrategy":"Default","decodingStrategy":"None","key":"secret/data/gitlab/ci-variables","metadataPolicy":"None","property":"harbor_robot_password"},"secretKey":"HARBOR_PASSWORD"},{"remoteRef":{"conversionStrategy":"Default","decodingStrategy":"None","key":"secret/data/gitlab/ci-variables","metadataPolicy":"None","property":"sonar_host_url"},"secretKey":"SONAR_HOST_URL"},{"remoteRef":{"conversionStrategy":"Default","decodingStrategy":"None","key":"secret/data/gitlab/ci-variables","metadataPolicy":"None","property":"sonar_token"},"secretKey":"SONAR_TOKEN"}],"refreshInterval":"1h","secretStoreRef":{"kind":"ClusterSecretStore","name":"vault-backend"},"target":{"creationPolicy":"Owner","deletionPolicy":"Retain","name":"gitlab-ci-credentials"}},"status":{"binding":{"name":"gitlab-ci-credentials"},"conditions":[{"lastTransitionTime":"2026-02-24T10:32:08Z","message":"Secret was synced","reason":"SecretSynced","status":"True","type":"Ready"}],"refreshTime":"2026-02-24T17:32:14Z","syncedResourceVersion":"1-2f2c636d06132f67992c15a1daeb0a5f"}}
    creationTimestamp: "2026-02-24T19:47:16Z"
    generation: 1
    name: gitlab-ci-credentials
    namespace: gitlab-staging
    resourceVersion: "11826196"
    uid: 0773793a-97d1-427c-8b07-3051b1d6344d
  spec:
    data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secret/data/gitlab/ci-variables
        metadataPolicy: None
        property: harbor_registry_url
      secretKey: HARBOR_REGISTRY
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secret/data/gitlab/ci-variables
        metadataPolicy: None
        property: harbor_robot_user
      secretKey: HARBOR_USER
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secret/data/gitlab/ci-variables
        metadataPolicy: None
        property: harbor_robot_password
      secretKey: HARBOR_PASSWORD
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secret/data/gitlab/ci-variables
        metadataPolicy: None
        property: sonar_host_url
      secretKey: SONAR_HOST_URL
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secret/data/gitlab/ci-variables
        metadataPolicy: None
        property: sonar_token
      secretKey: SONAR_TOKEN
    refreshInterval: 1h
    secretStoreRef:
      kind: ClusterSecretStore
      name: vault-backend
    target:
      creationPolicy: Owner
      deletionPolicy: Retain
      name: gitlab-ci-credentials
  status:
    binding:
      name: gitlab-ci-credentials
    conditions:
    - lastTransitionTime: "2026-02-25T10:32:32Z"
      message: secret synced
      reason: SecretSynced
      status: "True"
      type: Ready
    refreshTime: "2026-02-25T12:32:32Z"
    syncedResourceVersion: 1-d95f85af2d579ee17dfdc2e73ab40ca4
kind: List
metadata:
  resourceVersion: ""
