apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ${name}
  namespace: ${namespace}
  labels:
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/component: disruption-budget
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: opentelemetry-collector
      app.kubernetes.io/instance: ${name}
