#!/bin/bash
# scripts/finops/weekly-cost-report.sh
#
# Generate weekly AWS cost report using Cost Explorer API.
# Outputs JSON report and summary to stdout.
#
# Usage:
#   bash scripts/finops/weekly-cost-report.sh              # last 7 days
#   bash scripts/finops/weekly-cost-report.sh 30            # last 30 days
#
# Requires: aws-cli, jq, active AWS SSO session
# Note: Cost Explorer API has a charge of $0.01 per request

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Read config from platform-config.yaml if yq is available
if command -v yq &>/dev/null && [ -f "$PROJECT_ROOT/platform-config.yaml" ]; then
  PROFILE=$(yq eval '.aws.profile' "$PROJECT_ROOT/platform-config.yaml")
else
  PROFILE="${AWS_PROFILE:-default}"
fi

DAYS="${1:-7}"
START_DATE=$(date -d "${DAYS} days ago" +%Y-%m-%d 2>/dev/null || date -v-${DAYS}d +%Y-%m-%d)
END_DATE=$(date +%Y-%m-%d)

REPORT_DIR="$PROJECT_ROOT/reports/aws-costs"
REPORT_FILE="$REPORT_DIR/weekly-${END_DATE}.json"
SUMMARY_FILE="$REPORT_DIR/weekly-${END_DATE}-summary.md"

mkdir -p "$REPORT_DIR"

echo "=========================================="
echo " FinOps Weekly Cost Report"
echo "=========================================="
echo "Period:   $START_DATE to $END_DATE ($DAYS days)"
echo "Profile:  $PROFILE"
echo "=========================================="

# --- 1. Cost by Service (daily granularity) ---
echo ""
echo "Fetching cost data by service..."

aws ce get-cost-and-usage \
  --profile "$PROFILE" \
  --time-period "Start=${START_DATE},End=${END_DATE}" \
  --granularity DAILY \
  --metrics "UnblendedCost" "UsageQuantity" \
  --group-by Type=DIMENSION,Key=SERVICE \
  --output json > "$REPORT_FILE"

echo "Raw report saved: $REPORT_FILE"

# --- 2. Calculate totals ---
echo ""
echo "--- Cost Summary ---"

TOTAL=$(jq -r '[.ResultsByTime[].Groups[].Metrics.UnblendedCost.Amount | tonumber] | add | . * 100 | round / 100' "$REPORT_FILE")
DAILY_AVG=$(echo "$TOTAL $DAYS" | awk '{printf "%.2f", $1/$2}')
MONTHLY_PROJ=$(echo "$DAILY_AVG" | awk '{printf "%.2f", $1 * 30}')

echo "Total ($DAYS days):      \$${TOTAL}"
echo "Daily average:           \$${DAILY_AVG}"
echo "Monthly projection:      \$${MONTHLY_PROJ}"

# --- 3. Top services ---
echo ""
echo "--- Top 10 Services ---"

TOP_SERVICES=$(jq -r '
  [.ResultsByTime[].Groups[] | {service: .Keys[0], cost: (.Metrics.UnblendedCost.Amount | tonumber)}]
  | group_by(.service)
  | map({service: .[0].service, total: (map(.cost) | add)})
  | sort_by(-.total)
  | .[:10]
  | .[]
  | "\(.service)|\(.total | . * 100 | round / 100)"
' "$REPORT_FILE")

printf "%-40s %10s\n" "Service" "Cost (USD)"
printf "%-40s %10s\n" "--------" "----------"
echo "$TOP_SERVICES" | while IFS='|' read -r SVC COST; do
  printf "%-40s %10s\n" "$SVC" "\$$COST"
done

# --- 4. Daily trend ---
echo ""
echo "--- Daily Trend ---"

DAILY_TREND=$(jq -r '
  .ResultsByTime[]
  | {date: .TimePeriod.Start, total: ([.Groups[].Metrics.UnblendedCost.Amount | tonumber] | add | . * 100 | round / 100)}
  | "\(.date)|\(.total)"
' "$REPORT_FILE")

printf "%-12s %10s\n" "Date" "Cost (USD)"
printf "%-12s %10s\n" "--------" "----------"
echo "$DAILY_TREND" | while IFS='|' read -r DATE COST; do
  printf "%-12s %10s\n" "$DATE" "\$$COST"
done

# --- 5. Generate markdown summary ---
cat > "$SUMMARY_FILE" << EOF
# Weekly Cost Report — ${START_DATE} to ${END_DATE}

| Metric | Value |
|--------|-------|
| Period | ${START_DATE} to ${END_DATE} (${DAYS} days) |
| Total Cost | \$${TOTAL} USD |
| Daily Average | \$${DAILY_AVG} USD |
| Monthly Projection | \$${MONTHLY_PROJ} USD |
| Generated | $(date --iso-8601=seconds) |

## Top Services

| Service | Cost (USD) |
|---------|-----------|
$(echo "$TOP_SERVICES" | while IFS='|' read -r SVC COST; do echo "| ${SVC} | \$${COST} |"; done)

## Daily Trend

| Date | Cost (USD) |
|------|-----------|
$(echo "$DAILY_TREND" | while IFS='|' read -r DATE COST; do echo "| ${DATE} | \$${COST} |"; done)

---
*Generated by scripts/finops/weekly-cost-report.sh*
EOF

echo ""
echo "Summary saved: $SUMMARY_FILE"
echo "=========================================="
echo " Report complete"
echo "=========================================="
